
inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_rails.yml
#  - .rubocop_rspec.yml
  - .rubocop_strict.yml
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/schema.rb
    - db/migrate/*.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*